build:

build_script:
  - mkdir build && cd build
  - cmake -G "Visual Studio %TOOLCHAIN_VERSION% Win64" ..
  - cmake --build . --config %BUILD_TYPE%

environment:
  PYTHON: "C:\\Python27"
  PYTHON_VERSION: "2.7.8"
  PYTHON_ARCH: "32"
  matrix:
    - TOOLCHAIN_VERSION: 14
      BUILD_TYPE: Release

artifacts:
    - path: build\Release\mrandrb-ask-n-ans.exe


#    - path: '**\*.exe'

#    - path: build\$(configuration)\mrandrb-ask-n-ans.exe

deploy:
    # выкладываем tagged-коммиты на GitHub Releases:
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    provider: GitHub

    auth_token:
        secure: 8RbKKxAbtv4F943f2bk2dKMRU7X2uw81nQetHMUpWN+aFl133aTRRH6SMrtqyZR6

    artifact: /.*\.pkg/
    force_update: true

    on:
        appveyor_repo_tag: true